godot-nim/gdext-nim

- src/godot.nim
> rename godot.echo to print and hide generated one

- src/godot.nim
- src/godot/classautomate/contracts.nim
- src/godot/extensionmanager.nim
> Reports whether the class has been registered correctly

- src/config.nims
- src/godot.nim
- src/godot/checkenv.nim
> Check the application type and warn

- src/godot/init.nim
godot-nim/godotcore#19
godot-nim/coronation#5
> Load godot APIs before NimMain()

- src/gdext/extensionmanager.nim
> Change the name of ExtensionManager for each extension.

- src/gdext/classautomate/methodinfo.nim
godot-nim/gdextcore#22
godot-nim/coronation#8
fixes #28
> Handle Exception at function endpoints

- src/gdext/classautomate/contracts.nim
- src/gdext/classautomate/procs.nim
- src/gdext/classautomate/properties.nim
- src/gdext/classautomate/signals.nim
- src/gdext/classautomate/virtuals.nim
- src/gdext/extensionmanager.nim
- src/gdext/gdextensionmain.nim
- src/gdext/init.nim
now we can instantiate MyClass at top-level.
> Change class registration process to staticevents

- src/gdext/classautomate.nim
- src/gdext/classautomate/virtuals.nim
- src/gdext/gdextensionmain.nim
- src/gdext/init.nim
- test/nim/tests.gdextension
- test/project.godot
> Support hotreload

- src/nim.cfg
- test/nim/config.nims
Fix fatal error to install at first time.
Related to #66 
Fixes #65
> Fix: add path to work with absolute path

- src/gdext.nim
- src/gdext/core/userclass/contracts.nim
- src/gdext/core/userclass/procs.nim
- src/gdext/core/userclass/signals.nim
- src/gdext/surface/init.nim
- src/gdext/surface/properties.nim
- src/gdext/surface/userclass.nim
- src/gdext/utils/staticevents.nim
- test/nim/bootstrap.nim
- test/nim/src/classes/gdproptestnode.nim
- test/nim/src/godotSideTester.nim
Unified syntax of staticevents into function definitions to improve readability.
Simplified internal processing, improving compile time by several percent.
> Refactor staticevents

- src/gdext.nim
- src/gdext/surface/userenums.nim
- test/nim/bootstrap.nim
- test/nim/src/cases/enums.nim
https://github.com/godot-nim/gdext-nim/blob/0f2d7ac7c25e5ad4695c6927ec9c2f6df7744569/test/nim/src/cases/enums.nim#L1-L21
> Feat: enable to register user enum

- .gitignore
- src/gdext/wizard/subcommands/extension/template/.gdextension
- test/nim/tests.gdextension
See https://github.com/godot-nim/gdext-nim/issues/70 for explanation/rationale
> Workaround for test project hot-reload on macOS

- src/gdext/core/userclass/procs.nim
Fix #78
See also godot-nim/gdextgen#3
> Fix: normalize method ident

- src/gdext/gdextwiz.nim
- src/gdext/wizard/subcommands/iteration.nim
Usage:
```console
gdext-nim$ gdextwiz run test
```
```console
gdext-nim/test$ gdextwiz run
```
Above both will compile extensions and launch godot.
See help message for more detail.
> add `run` command

- README.md
- src/gdext/buildconf.nim
> Revert changes about building for windows and update README

- src/gdext/surface/classutils.nim
- test/main.tscn
- test/nim/src/classes/gdproptestnode.nim
- test/nim/src/classes/gdproptestnode_pragmas.nim
> Fix incorrect reference counting with cast to

- src/gdext/core/gdclass.nim
- src/gdext/surface/userclass.nim
- testproject/editor/main.tscn
- testproject/editor/nim/bootstrap.nim
- testproject/editor/nim/src/classes/gdsignalpublisher.nim
- testproject/editor/nim/src/classes/gdsignalsubscriber.nim
There is code in testproject/editor that has been made to work with this PR.
> Fix broken object bindings while hotreloading

- gdext.nimble
- src/gdext/surface/arrayutils.nim
- testproject/runtime/nim/src/cases/array.nim
> Feat: PackedArray.toSeq

- src/gdext/core/methodtools.nim
- testproject/runtime/nim/src/cases/issues.nim
Fix crash due to mis-synchronization of reference counts.
Fixes #134
> Fix reference counting

- src/gdext/surface/arrayutils.nim
- testproject/runtime/nim/src/cases/primitives.nim
Implement (m)items and (m)pairs iterators for PackedArray[T] and Array.
> Feat: add iterators for Array kinds

- src/gdext/gdinterface/objects.nim
- src/gdext/surface/classutils.nim
- src/gdext/surface/nodeutils.nim
- src/gdext/surface/variantutils.nim
- testproject/runtime/nim/src/classes/gdextnode/typedef.nim
Fix object stringing failure due to earlier refactoring and add more test items.
> Fix: object stringification

- src/gdext.nim
- testproject/runtime/nim/bootstrap.nim
- testproject/runtime/nim/src/cases/prints.nim
relates: #150 
Same as above, add `printerr(vararg[Variant])`.
> Feat: printerr(varargs)
