- src/godot/classautomate/checkform.nim
- src/godot/classautomate/procs.nim
- src/godot/classautomate/signals.nim
- src/godot/classautomate/virtuals.nim
This PR is to ensure that an easy-to-understand error is displayed for incorrect definitions such as the following:
```nim
proc myproc*() {.gdsync.} = discard
proc myproc*(x: int) {.gdsync.} = discard
```
```nim
import std/times
proc myproc*(self: ValidClass; x: times.Time) {.gdsync.} = discard
```
```nim
proc mysignal*(self: ValidClass) {.gdsync, signal.}
proc mysignal*(self: ValidClass): int {.gdsync, signal.}
```
> Clarify basic gdsync errors

- src/godot.nim
- src/godot/extensionmanager.nim
This PR is intended to enable the following operations:
```nim
method ready*(self: MyClass) {.gdsync.} =
if isRunningInEditor:
print "initialization omitted"
else:
self.window = self.getWindow()
self.connect("signal", self.callable"callback")
...
```
closes #13
> Add: isRunningInEditor predicate

- src/gdext/env.nim
Change projectName to be taken from the Nim build system, so that it does not need to be specified in bootstrapconf.nims.
> Get projectName internally

- src/gdext.nim
- src/gdext/classautomate.nim
- src/gdext/classautomate/procs.nim
- src/gdext/classautomate/properties.nim
- src/gdext/classautomate/propertyinfo.nim
- test/main.tscn
- test/nim/bootstrap.nim
- test/nim/src/classes/gdproptestnode.nim
- test/nim/src/godotSideTester.nim
> 54 assort export annotations

- src/gdext.nim
- src/gdext/core/varianttools.nim
- src/gdext/surface/conversions.nim
- src/gdext/surface/variantutils.nim
- test/main.tscn
- test/nim/bootstrap.nim
- test/nim/src/cases/array.nim
- test/nim/src/cases/use_api_from_toplevel.nim
- test/nim/src/cases/variant.nim
- test/nim/src/classes/gdnimsidetester/typedef.nim
- test/nim/src/classes/gdproptestnode.nim
- test/tester.gd
Referring to godot-cpp, add a set of API functions to make it easier to handle variants from Nim.
Functions Added:
```nim
proc evaluate*(op: VariantOperator; a, b: ptr Variant; valid: var bool): Variant
proc evaluate*(op: VariantOperator; a, b: ptr Variant): Variant
proc `==`*(self, other: Variant): bool
proc `!=`*(self, other: Variant): bool
proc `<`*(self, other: Variant): bool
proc `<=`*(self, other: Variant): bool
proc `>`*(self, other: Variant): bool
proc `>=`*(self, other: Variant): bool
proc contains*(self: Variant; index: Variant): bool
proc call*(self: Variant; `method`: StringName; err: var CallError; args: varargs[Variant, variant]): Variant {.discardable.}
proc call*(self: Variant; `method`: StringName; args: varargs[Variant, variant]): Variant {.discardable.}
proc …
```
> Enhance variant operations

- README.md
- gdext.nimble
- src/gdext.nim
- src/gdext/buildconf.nim
- src/gdext/classes/gdextensionmain.nim
- src/gdext/core/userclass/propertyinfo.nim
- src/gdext/core/userclass/signals.nim
- src/gdext/surface/arrayutils.nim
- src/gdext/surface/conversions.nim
- src/gdext/surface/init.nim
- src/gdext/surface/nodeutils.nim
- src/gdext/surface/properties.nim
- src/gdext/wizard/subcommands/library.nim
- test/nim/src/classes/gdextnode/typedef.nim
- test/nim/src/classes/gdproptestnode.nim
Reverses the dependency between gdextgen and gdext and changes the gdextgen installation to require gdext.
In the previous package configuration, it was difficult to switch between target engine versions.
That would be accomplished by changing gdextgen, but that is not possible because a fixed version of gdextgen is required by gdext. Every time you tried to switch versions, you had to rewrite the requires in gdext.nimble and had to use `git clone` instead of `nimble install` for that.
With this PR, to switch versions, simply uninstall the current gdextgen (at this point, gdext will remain in local) and reinstall another gdextgen.
Furthermore, the root directory of the gdextgen package was changed to gdext. This allows, for example, when importing a class, to simply write `import …
> Invert dependency with gdextgen

- src/gdext/gdextwiz.nim
- src/gdext/wizard/subcommands/iteration.nim
* Change what the run command executes from build-all to build
* If the command fails midway, subsequent processing is aborted.
Example: If the build of an extension fails during the execution of the run command, godot is not started.
* `gdextwiz editor`
Find project.godot in the direction of the parent directory and run godot --editor.
* `gdextwiz run-editor`
After `run`, exec `editor`.
> Add editor commands

- src/gdext/core/typeshift.nim
- src/gdext/core/userclass/methodinfo.nim
- src/gdext/core/userclass/procs.nim
- src/gdext/core/userclass/propertyinfo.nim
- src/gdext/utils/macros.nim
- test/nim/src/classes/gdextnode/functions.nim
- test/tester.gd
```nim
proc varargs_variant(self: typedesc[GDExtNode]; args: varargs[ptr Variant]): string {.gdsync.} =
args.mapIt(it[].get int).join(", ")
proc varargs_concrete(self: typedesc[GDExtNode]; args: varargs[int]): string {.gdsync.} =
args.join(", ")
```
```gdscript
assert(GDExtNode.varargs_variant(1, 2, 3, 4, 5) == "1, 2, 3, 4, 5")
assert(GDExtNode.varargs_concrete(1, 2, 3, 4, 5) == "1, 2, 3, 4, 5")
```
> Feat(library): support to export varargs[ptr Variant]

- src/gdext/core/builtinindex.nim
Reported in #98.
Fix access errors caused by differences in Variant state management and disposal methods between the engine and the library.
> Fix variant destruction

- src/gdext/core/geometrics/typedef.nim
- tests/testgeometrics.nim
Implements #109 
My originally suggested code worked fine, except `nim check` wouldn't detect `v2.z` as an error. Compiling would fail though. The same issue reemerged with the `compiles` check for the unittesting because it also wouldn't detect the error.
I tried using range[] generics but there might be nim bugs. I was able to contrive a working example, where `nim check` would detect incorrect access, but it didn't seem like a good idea to rely on potentially bugged code, and I believe `compiles` still accepted incorrect access.
I made an other version using `concept` but I don't have enough experience with them and wasn't able to consolidate them into a single generic concept type like I wanted.
In the end, I settled for a `macro` which simply generates the templates for the different …
> Vector field access

- coronation/src/coronation/operators/classes/properties.nim
- coronation/src/coronation/operators/classindex.nim
- src/gdext/classes.nim
- src/gdext/classes/gdaudiostreamplaylist.nim
- src/gdext/classes/gdbasematerial3d.nim
- src/gdext/classes/gdcamera2d.nim
- src/gdext/classes/gdconetwistjoint3d.nim
- src/gdext/classes/gdcontrol.nim
- src/gdext/classes/gdcpuparticles2d.nim
- src/gdext/classes/gdcpuparticles3d.nim
- src/gdext/classes/gddecal.nim
- src/gdext/classes/gdgpuparticles3d.nim
- src/gdext/classes/gdimage.nim
- src/gdext/classes/gdlabel3d.nim
- src/gdext/classes/gdlight3d.nim
- src/gdext/classes/gdninepatchrect.nim
- src/gdext/classes/gdnode.nim
- src/gdext/classes/gdparticleprocessmaterial.nim
- src/gdext/classes/gdphysicsbody3d.nim
- src/gdext/classes/gdrdshadersource.nim
- src/gdext/classes/gdrdshaderspirv.nim
- src/gdext/classes/gdspritebase3d.nim
- src/gdext/classes/gdstylebox.nim
- src/gdext/classes/gdstyleboxflat.nim
- src/gdext/classes/gdstyleboxtexture.nim
- src/gdext/classes/gdtextureprogressbar.nim
- src/gdext/classes/gdviewport.nim
- src/gdext/classes/gdwindow.nim
- src/gdext/surface/classutils.nim
Fixes #125 
Fixes a problem in which properties that access with index internally cause compile errors.
Caused by passing a magic number when an enum should have been passed.
And solved by expanding to enum at the stage of generating bindings.
> Fix indexed properties

- src/gdext/core/userclass/contracts.nim
- src/gdext/core/userclass/methodinfo.nim
- src/gdext/core/userclass/procs.nim
- src/gdext/core/userclass/virtuals.nim
- src/gdext/surface/userclass.nim
- testproject/runtime/inherited_node01.gd
- testproject/runtime/inherited_node02.gd
- testproject/runtime/main.gd
- testproject/runtime/main.tscn
- testproject/runtime/nim/bootstrap.nim
- testproject/runtime/nim/src/classes/gdextnode/typedef.nim
- testproject/runtime/nim/src/classes/gdvirtualnode01.nim
- testproject/runtime/nim/src/classes/gdvirtualnode02.nim
Support the definition of new virtual functions and the invocation of overridden virtual functions in GDScript.
The following operations are **not** supported:
* Calling virtual functions defined in Nim from GDScript without overriding them in itself
Register the base method with Godot by marking the method with the {.gdsync, base.} pragma.
Default behavior can be set for virtual functions.
https://github.com/godot-nim/gdext-nim/blob/15331967c3fabd410e7d2f2c86df716b56cac24b/testproject/runtime/nim/src/classes/gdvirtualnode01.nim#L1-L7
Override as well as engine built-in methods such as ready.
https://github.com/godot-nim/gdext-nim/blob/15331967c3fabd410e7d2f2c86df716b56cac24b/testproject/runtime/nim/src/classes/gdvirtualnode02.nim#L1-L9
The name you define will be published in the …
> Feat: support to register virtual method

- src/gdext/core/gdclass.nim
- src/gdext/core/userclass/methodinfo.nim
- src/gdext/core/userclass/propertyinfo.nim
- src/gdext/core/userclass/signals.nim
- src/gdext/surface/properties.nim
Until now, PropertyInfo has been created in the stack area, but we have found that if we need to use the PropertyInfo we have created around, there is a potential problem with it being destroyed once it leaves the scope.
This PR does not fix the specific bug that is happening now, but is a change for the future.
> Fix(internal): allocate property info

- src/gdext/core/userclass/procs.nim
- src/gdext/core/userclass/signals.nim
- src/gdext/core/userclass/tools.nim
Organize function synchronization macros that had become spaghetti.
There are no changes in functionality.
> Refactor: improve signal/proc-generation's readability

- src/gdext.nim
Like the print function, the printRich function is overloaded to allow arbitrary arguments (convertible to Variant) to be passed.
> Feat: printRich(varargs)

- src/gdext/surface/init.nim
- src/gdext/surface/userclass.nim
- src/gdext/wizard/subcommands/extension.nim
- src/gdext/wizard/subcommands/extension/template/bootstrap.nim
- src/gdext/wizard/subcommands/extension/template/src/classes/gdmyclass.nim
Allow {.gdsync.} to be passed when defining extended classes.
Classes that are {.gdsync.} are implicitly registered with the engine.
As a byproduct, the register_classes function can be removed from bootstrap.nim.
The traditional registration mechanism is still available.
Example:
```nim
import gdext
type MyClass* {.gdsync.} = ptr object of Node
GDExtensionEntryPoint
```
> Feat: gdsync for TypeDef. That will register the class implicitly.

- src/gdext/gdinterface/extracommands.nim
- testproject/runtime/nim/src/cases/primitives.nim
Fixes a bug that caused garbled characters when strings containing multibyte characters such as Japanese and Chinese are converted to Godot.String, enabling multilingual support.
As a byproduct, String can be treated like seq[unicode.Rune].
Although it is necessary to import std/unicode separately, Rune can be obtained by iterating over the String, so Kanji characters, etc., can be correctly processed one by one.
> Feat: Variable-width encoding

- src/gdext/surface/userclass.nim
- testproject/runtime/nim/src/classes/gdextnode/functions.nim
Fixes a bug that when {.gdsync.} is added to a forward declaration, it is interpreted as an actual function declaration and the registration process is duplicated.
If {.gdsync.} is appended to the forward declaration, this pragma is ignored and a hint is output instead.
> Fix: Ignore {.gdsync.} appended to the forward declaration.

- src/gdext/core/typeshift.nim
- src/gdext/core/userclass/propertyinfo.nim
- testproject/runtime/main.gd
- testproject/runtime/nim/src/classes/gdextnode/enums.nim
set[enum] is now available as a property, argument, and return value. From the editor (as with enum), it is treated as an Int value with a name.
> Feat: set[enum] for properties

- src/gdext/surface/userenums.nim
- testproject/editor/nim/src/classes/gdproptestnode.nim
- testproject/editor/nim/src/classes/gdproptestnode_pragmas.nim
- testproject/runtime/nim/src/classes/gdextnode/enums.nim
Removed registerEnum and registerBitField functions and replaced them with bind functions: passing enum to bind will register it as an enum, and passing set[enum] will register it as a bitfield.
Example:
```nim
import gdext
type
MyNode {.gdsync.} = ptr object of Node
testEnum* {.gdexport.}: TestEnum = Enum2
testFlags* {.gdexport.}: set[TestFlags] = {Flag2}
TestEnum = enum
Enum1 
Enum2 = 2
Enum3
TestFlags = enum # Values in Godot:
Flag1     # => 1
Flag2 = 2 # => 4
Flag3     # => 8
Flag4     # => 16
Flag5     # => 32
MyNode.bind TestEnum
MyNode.bind set[TestFlags]
```
> Destructive: Change `registerEnum/BitField(enum)` to `bind(enum/set[enum])`

- src/gdext/core/userclass/propertyinfo.nim
- src/gdext/surface/properties.nim
- src/gdext/utils/macros.nim
- testproject/editor/nim/src/classes/gdproptestnode.nim
- testproject/runtime/nim/src/classes/gdextnode/enums.nim
When you gdexport an enum or set[enum], what you see in the inspector so far is just a number.
This PR generates a hint string when registering a property so that it will be displayed in the inspector in the proper form.
Example:
```nim
import gdext
type
PropTestNode* {.gdsync.} = ptr object of Node
propTestFlags* {.gdexport.}: set[PropTestFlags]
propTestEnum* {.gdexport.}: PropTestEnum
PropTestFlags* = enum
PropTestFlag1, PropTestFlag2 = 10, PropTestFlag3
PropTestEnum* = enum
PropTestEnum1, PropTestEnum2 = 10, PropTestEnum3
PropTestNode.bind set[PropTestFlags]
PropTestNode.bind PropTestEnum
```
> Feat: Pretty up the appearance of enums and sets in the editor inspecor.

- src/gdext/surface/properties.nim
- testproject/editor/nim/src/classes/gdproptestnode.nim
Restricts the numbers on Inspector to not go outside the range defined by range when the range type is gdexport'ed.
> Feat: Limit the input range on the inspector for exported range types.

- src/gdext/core/userclass/procs.nim
- src/gdext/core/userclass/virtuals.nim
- src/gdext/surface/userclass.nim
To clarify the error displayed when trying to override an undefined (or unimported) virtual method with {.gdsync.}.
```nim
import gdext
import gdext/classes/gdObject
type TestObject* = ptr object of Object
method ready*(self: TestObject) {.gdsync.} = discard
```
```terminal
Error: The ready method of the parent class cannot be called. Verify that the method exists, that the
name is correct, and that the class module declaring the method is imported.
```
> Feat: Improve error messages when attempting to override undefined methods.
